name: test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix fmt -- --ci
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}
          path: /nix/store
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dldt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Remove conflicting Python framework on MacOS
        run: sudo rm -fr /Library/Frameworks/Python.framework
        if: ${{ runner.os == 'macOS' }}
      - run: nix flake check --accept-flake-config
      - uses: actions/cache/save@v4
        if: github.event_name == 'pull_request'
        with:
          key: ${{ runner.os }}
          path: |
            /nix/store
