name: test
on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix fmt -- --ci
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: x86_64-linux
            check: packages
          - os: ubuntu-latest
            platform: x86_64-linux
            check: packagesCuda
          - os: macos-latest
            platform: aarch64-darwin
            check: packages
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: dldt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Remove conflicting Python framework on MacOS
        run: sudo rm -fr /Library/Frameworks/Python.framework
        if: ${{ runner.os == 'macOS' }}
      - name: Nix flake check --no-build
        run: nix flake check --accept-flake-config --no-build
      - name: Nix flake check ${{ matrix.check }} on ${{ matrix.platform }}
        run: nix flake check --accept-flake-config --arg-from-file ./flake.nix checks.${{ matrix.platform }}.${{ matrix.check }}
